name: auto_update
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bluesky: ^0.3.3
  html: ^0.15.1
  http: ^0.13.5
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
