name: auto_update
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  bluesky: ^0.15.18
  html: ^0.15.1
  http: ^1.2.1
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
